### ISSUE TITLE
Input string was not in a correct format exception

### ISSUE THREAD

**Issue by bpaczkowski** [71/spotify-lyrics-windows#3]
I'm getting this exception when starting the app:

```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Lyrics.Helpers.JSON.parse(String s, Int32& i)
   at Lyrics.Helpers.JSON.parse(String s, Int32& i)
   at Lyrics.Helpers.JSON.parse(String s, Int32& i)
   at Lyrics.Helpers.JSON.parse(String s, Int32& i)
   at Lyrics.Musixmatch.parseSubtitles(String json, List`1 subtitles)
   at Lyrics.Musixmatch.getLyrics@103.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncPrimitives.Start@938-1.Invoke(ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Async.-ctor@167-1.Invoke(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by 71** [comment]
Hey,

Can you tell me what song caused a problem? Is your computer in English?

**Comment by bpaczkowski** [comment]
Yes, in English. I think all of the songs cause this. If that helps I can send a json from the cache, though it seems to be a valid json.

**Comment by 71** [comment]
I checked just in case and I can still read lyrics without issue on an English system, so I'd appreciate it if you sent a song from the cache for me to review.

Can you compile the project yourself? I have an idea that might work if the problem doesn't come from the JSON, but since everything works on my computer I can't try it out.

**Comment by bpaczkowski** [comment]
I did compile it, I even tried to debug it, but coming from C# background, F# looks like something from another world to me :) The issue was the same by the way.

[artist=Epica.track=Storm The Sorrow.json.zip](https://github.com/71/spotify-lyrics-windows/files/3774979/artist.Epica.track.Storm.The.Sorrow.json.zip)

**Comment by 71** [comment]
The JSON does look good to me; can you compile the latest version (45360a05db26aea818be53933e758c624ace6418) and see if things work now?

Edit: Since your system is in English I doubt it will change anything, but it's worth trying. F# certainly is different, but after many years of only doing C#, I now use F# for all my .NET needs. I highly recommend it if you have some free time :)

**Comment by bpaczkowski** [comment]
Ahh I know what it is! Even though my system is in English, the regional settings are set to a country where the decimal place separator is a comma not a dot. Yes, this did fix the issue.

On a sidenote, may I ask why you are using a custom solution for the JSON parsing?

**Comment by 71** [comment]
Ah, that makes more sense now! I always forget to use `CultureInfo.InvariantCulture`, even though my native language also uses commas instead of dots as decimal separators.

I always spend way too much time comparing the different JSON parsers around and thought that making my own would be faster. It's pretty bad to reinvent the wheel like that, but it saved me hours of comparisons. :) Plus I felt bad packaging a large JSON parser with it, knowing that 5% of its features would be used in the end.

**Comment by bpaczkowski** [comment]
.NET now includes a JSON parser since .NET Core 3.0 (System.Text.Json), it's pretty barebones at the moment but it's a good alternative to the other overgrown parsers.

Anyway, since the issue is resolved I think you can close it, unless you want to wait until it is released in a new version.

**Comment by 71** [comment]
I want to keep supporting .NET 4.5 so that's not available to me, but thanks for the tip!
